### PR TITLE
Fixed the Delete CSS Button in Settings

### PR DESCRIPTION
**Pull request by PrakharUniyal**
---

**What's this PR do?**
Fixes the alignment and look of the Delete "CSS from an external file" button.

**Any background context you want to provide?**
Issue: [#801 ](https://github.com/zulip/zulip-desktop/issues/801)

**Screenshots?**
zulipchangeddelbuton

**You have tested this PR on:**
  - [ ] Windows
  - [x] Linux/Ubuntu
  - [ ] macOS

### CODE REVIEW

**Comment by vsvipul** [comment]
Remove the package-lock changes from your PR.

**Comment by PrakharUniyal** [comment]
@vsvipul I've replaced the previous commit with a new one. I have a question though, why was that package-lock file updated even when I didn't edit it. Also, for some reason, a couple of icon files got modified(and are a part of this new commit). Should I remove them as well?

**Comment by akashnimare** [comment]
Looks like you have also changed the icons. Can you update the PR with only relevant changes? Also, it's a good idea to create a branch from your fork and then open a PR against the upstream.

**Comment by akashnimare** [comment]
> Should I remove them as well?

Yes, please.

**Comment by priyank-p** [comment]
@PrakharUniyal looks like you forced pushed master branch removing the commit you added which caused github to close this PR. I took a closer look into your changes I belive [this commit has the changed you wanted to include in this PR.](https://github.com/PrakharUniyal/zulip-desktop/commit/1370bc4b2b662b68da09f87ee7cdcd1747c844b0) Which has one minor issue, it removes the icon which I think we want here. So I extended the changes to not removed the icon and fixed it, [see this commit](https://github.com/zulip/zulip-desktop/pull/804/commits/a5e7f27c4309a44a605d37e14d89e9bed06c34d7) for more details.

If you need a good guide for working with git, zulip has a great resource you might be intrested in: https://zulip.readthedocs.io/en/latest/git/index.html#git-guide.

Thanks @PrakharUniyal for working on this, and your changes should be merged in #804.

**Pull request closed without merging**
