### PR TITLE
add missing debian/ubuntu dependancy

### PR DESCRIPTION
**Pull request by blinfoldking**
---

**Adding libgconf-2-4**

simply adding libgconf-2-4 into the debian/ubuntu dependancies install script

### CODE REVIEW

**Comment by akashnimare** [comment]
@BlinfoldKing I'm not sure if we need this dependency.

**Comment by blinfoldking** [comment]
i've got an error libconf-2-4 error when running the development install, i've also try this in other machine.

my machine runs ubuntu 17.10

it's also been refrencing in https://github.com/electron/electron-quick-start/issues/186

**Comment by akashnimare** [comment]
Hmm, correct. Looks like this dependency is required for `Ubuntu > 16.10`.

**Comment by blinfoldking** [comment]
it seems so

**Comment by akashnimare** [comment]
@BlinfoldKing merged. Thanks!

**Pull request merged**
