### PR TITLE
renderer: Improve loading spinner.

### PR DESCRIPTION
**Pull request by nooblag**
---

**What's this PR do?**
Improve loading GIF.

**Any background context you want to provide?**
Current GIF is archaic. 

**Screenshot**
simplescreenrecorder-2021-10-10

**You have tested this PR on:**

- [x] Windows
- [x] Linux/Ubuntu
- [ ] macOS

### CODE REVIEW

**Comment by andersk** [comment]
Please don’t open and close multiple separate pull requests for the same topic. You can always [update an existing pull request](https://zulip.readthedocs.io/en/latest/git/pull-requests.html#update-a-pull-request) by pushing to the same branch, using a force push if necessary.

The comment in the SVG points to loading.io, which has 4 available licenses. Which license is this one under?

**Comment by nooblag** [comment]
License for the [spinner](https://loading.io/spinner/rolling/-bar-circle-curve-round-rotate) is [Free](https://loading.io/license/#free-license)

**Comment by chrisbobbe** [comment]
Thanks, @nooblag!

I spend most of my time in the zulip/zulip-mobile repo, but I saw this and your [message in CZO](https://chat.zulip.org/#narrow/stream/16-desktop/topic/Improve.20loading.20GIF/near/1297490) and thought I might make a few comments that I hope will help move it along. 🙂

The answer to Anders's question about the license should appear in the code comment itself. It's a natural thing for someone to be curious about when they're looking at the code, not just when they're looking at this PR discussion in the GitHub UI. Most people reading the code won't go to GitHub and see this PR.

I see what look like two different changes in the one commit here:
1. A GIF file is changed.
2. An SVG file is added, and something starts pointing to it instead of the GIF file from (1).

I wonder if this should be two commits instead of one. Do the changes make more sense when seen together, or separately? See the [guide to clear and coherent commits](https://zulip.readthedocs.io/en/latest/contributing/version-control.html).

Does (2) remove the last reference to the GIF file? If so, why is the GIF file changed instead of removed? If not, where is the GIF file still used? Let's make the answers clear in the commit(s).

Since I work mostly on mobile, I've come to view the commit without the context of any previous discussion of its changes. Commits should be written to an audience that includes people who weren't part of any particular discussion. 🙂 It would be helpful to have a link to any previous discussion, in the commit message—but also I think it should be possible to summarize the reasons for the changes without relying on any previous discussion at all. A few words about why we think these particular changes improve the loading spinner would be great.

I see you've posted a screenshot above; great! If it were me, I'd mention that in the commit message, with a link, to make it easier for people to find. Including a link assumes GitHub will still exist and the link will still be valid at the time it's followed—but these assumptions should hold for a good long time.

**Comment by nooblag** [comment]
Heyas, I'm hoping now the Electron upgrade has been done, this PR can be merged to update the archaic spinner that is still hanging around ;)

**Comment by nooblag** [comment]
Hi there, any chance this will ever get merged?

**Comment by chrisbobbe** [comment]
It looks like it's still waiting for a response to my review, above. Also, the GitHub UI is reporting some failing CI checks, and the branch contains a merge commit (Zulip [doesn't use those](https://zulip.readthedocs.io/en/latest/git/troubleshooting.html#undo-a-merge-commit)).

**Comment by nooblag** [comment]
Hi there, thanks for getting back.

I have a few responses then.

The first regarding multiple commits. For background, in the past when I've donated my time and energy to making small improvements like this for Zulip, I've done so with multiple commits, but have been told that there are too many commits and that I should squash them into one (which is what I tried to do here). So not sure what to do here regarding conflicting information on that front. Likewise with the merge commit. I've followed the Zulip documentation on development (which also by the way mentions that merge commits aren't a bad thing) so I'm not sure what is desired here, pending further instructions on what I should be asking git to do in regards to each person's various preferences.

In regards to the license, am I essentially being asked to modify the spinner loading.io code to show its license? That could be done, and likewise with removing the GIF file entirely as a separate commit, if people accept the SVG instead, and that's what will get us to this PR being merged.

**Comment by chrisbobbe** [comment]
Our practice in the Zulip project is that “each commit is a minimal coherent idea”; details in [this doc](https://zulip.readthedocs.io/en/latest/contributing/commit-discipline.html). Sometimes that requires splitting one commit into multiple, sometimes squashing multiple commits into one.

Here's a suggestion: You could amend the commit to delete the GIF, with the idea being simply "replace an old GIF with a new SVG". Did you want to use the new version of the GIF for anything? (If so, where did it come from, when should it be used instead of the SVG, etc.?)

Please do remove the merge commit, following what the [doc](https://zulip.readthedocs.io/en/latest/git/troubleshooting.html#undo-a-merge-commit) says just after "merge commits aren’t bad":

> however, Zulip doesn’t use them. Instead Zulip uses a forked-repo, rebase-oriented workflow.

Please feel free to post in `#git help` in the [Zulip Development Community](https://zulip.com/development-community/) with any questions about how to use Git or how to apply our commit discipline.

For the license, I suggest writing your answer to Anders's question in a brief code comment in app/renderer/css/main.css, just above the line responsible for using the SVG file in the app. Since the comment starts being useful exactly when the app starts using the SVG, it makes sense to add that comment in the same commit.

**Comment by nooblag** [comment]
Hi @chrisbobbe Thanks for that. It's very helpful. How are these changes looking then?

**Comment by chrisbobbe** [comment]
Thanks for the revision! The history looks better now; the next step will be a review from @andersk.

**Comment by nooblag** [comment]
Okay great, thanks :)

**Comment by nooblag** [comment]
Just responding to the bot message. I can't see a conflict. Someone with write access want to have a look?

**Comment by nooblag** [comment]
A friendly ping on this.

**Comment by nooblag** [comment]
Dude, just say if you're never going to merge this, and I'll withdraw it. It shouldn't take years and years to accept PR for a spinner?

**Pull request merged**
