### PR TITLE
Issue/tab style

### PR DESCRIPTION
**Pull request by zhongyi-tong**
image
#210

### CODE REVIEW

**Comment by akashnimare** [comment]
How about putting the shortcut option outside of the server icon? We want to focus/highlight on the server icon.  

final

**Comment by zhongyi-tong** [comment]
I looks a little bit wired when the tab is not selected, Too much padding.
What do you think?
Akash Nimare <notifications@github.com>于2017年7月19日 周三上午5:00写道：

**Comment by akashnimare** [comment]
This overlaps with the icon.

image

If we set `right: 0px` then it will look good -

image

**Comment by akashnimare** [comment]
@geeeeeeeeek let's finalize this asap.

**Comment by zhongyi-tong** [comment]
Done.

**Comment by akashnimare** [comment]
Looks good. Thanks, @geeeeeeeeek 🚀

**Pull request merged**
