### PR TITLE
design: Improve existing organization design.

### PR DESCRIPTION
**Pull request by abhigyank**
Existing organisation details are now inline. Change "Delete" to "Disconnect". Club organisation logo and name together on the right, and url and "Disconnect" to the left.
Link to organisation logo to the server tab.

---

**What's this PR do?**

**Any background context you want to provide?**

**Screenshots?**
screenshot from 2018-03-07 03-12-11

**You have tested this PR on:**
  - [ ] Windows
  - [x] Linux/Ubuntu
  - [ ] macOS

### CODE REVIEW

**Comment by priyank-p** [comment]
The rows aren't too responsive.

screen shot 2018-03-07 at 2 44 24 pm

**Comment by priyank-p** [comment]
Also, commit msg has a typo `organisation` -> `organization`!

**Comment by abhigyank** [comment]
I'll check it out thanks.

**Comment by abhigyank** [comment]
Ping @akashnimare

**Comment by akashnimare** [comment]
Let's finish up `redesign-setting-page` first.

**Comment by abhigyank** [comment]
Should we be merging this to the `redesign-setting-page` branch?

**Comment by akashnimare** [comment]
@abhigyank can you rebase and fix merge conflicts? Also, you might need to tweaks the design since we recently updated the 'Existing Servers' section.

**Comment by akashnimare** [comment]
Merged with few more design tweaks. @abhigyank thanks 🚀

**Pull request merged**
