### PR TITLE
TODOs: TypeScript

### PR DESCRIPTION
**Pull request by akshatsachan**
---

**What's this PR do?**
In this PR I have completed 5 TODO: TypeScript tasks.
Along with that this PR also helps to partially fixes issue #860 .
The TODOs I have completed are -
1. TODO: TypeScript This type for props should be TabProps
in
app/renderer/js/components/functional-tab.ts
commit id- 7802143
2. TODO: TypeScript - Here props should be object type
in
app/renderer/js/pages/preference/base-section.ts
and
3. app/renderer/js/pages/preference/servers-section.ts
commit id- 4304f34
4. TODO: TypeScript This type for props should be TabProps
in
app/renderer/js/components/server-tab.ts
commit id- 3266696
5. TODO: TypeScript - Here props should be object type
in
app/renderer/js/pages/preference/nav.ts
commit id- d653856

**Any background context you want to provide?**
This is my first PR in this repository. I have taken up issue #860 and although there is more to do to complete this issue I have created this PR so that I could get to know about any mistakes that I might have commited early on in the development process.
**Screenshots?**

**You have tested this PR on:**
  - [ ] Windows
  - [ .] Linux/Ubuntu
  - [ ] macOS

### CODE REVIEW

**Comment by akashnimare** [comment]
LGTM. @vsvipul quick review?

**Comment by akshatsachan** [comment]
@akashnimare in case if @vsvipul  is not available can you please review and merge my PR.

**Comment by vsvipul** [comment]
Using ```[key: string]: any;``` everywhere is not the right way to do these PRs. You need to find out what properties that class has and then write the interface on the basis of that.

**Comment by manavmehta** [comment]
Hey @AkshatSachan I was already working on this issue and have already created a PR which is under review.

**Pull request closed without merging**
