### PR TITLE
build: add msi to build targets

### LINKED ISSUE #641: Provide MSI Installer
We have got few requests from users who want to have the MSI installer so that the admin can distribute the app easily to multiple machines -

https://www.electron.build/configuration/win#WindowsConfiguration-target

### PR DESCRIPTION
**Pull request by vsvipul**
**What's this PR do?**
Fixes #641 . 
You can test the generate msi file [here](https://drive.google.com/file/d/1zLpsoolYz-NwPxYGWrvON468jidlCTv8/view?usp=sharing) .

**You have tested this PR on:**
  - [x] Windows
  - [ ] Linux/Ubuntu
  - [ ] macOS

### CODE REVIEW

**Comment by akashnimare** [comment]
@vsvipul did you investigate on what files we need to put on the GitHub release in order to support the target?

**Comment by vsvipul** [comment]
@akashnimare i didn't require any files to be put up to build the msi file.

**Comment by vsvipul** [comment]
@akashnimare is this required anymore? If not, should i close this ?

**Comment by akashnimare** [comment]
I'll get back to this after the release.

**Comment by akashnimare** [comment]
Things we need to do here -
* Figure out what files we need to upload on the GitHub like in case of nsis we upload nsis.7z etc.
* Test the auto-update

**Comment by akashnimare** [comment]
> Figure out what files we need to upload on the GitHub like in case of nsis we upload nsis.7z etc.

There is only one file i.e. `Zulip-Web-Setup-x.x.x.msi`

> Test the auto-update

Auto-update doesn't work with MSI.

**Pull request merged**
