### PR TITLE
Removed the sidebar fluctuation on switching the toggle button

### PR DESCRIPTION
**Pull request by Shipragupta14**
slide

### CODE REVIEW

**Comment by Shipragupta14** [comment]
@akashnimare  please review and tell if there are any other improvements that needs to be done.

**Comment by akashnimare** [comment]
LGTM 👍

**Comment by akashnimare** [comment]
@Shipragupta14 I have reverted this since it doesn't hide the space of sidebar container. See - 

image

**Comment by akashnimare** [comment]
Fixed in https://github.com/zulip/zulip-electron/commit/ad5bef821e926bd050bd4ff1a1b0cbfb5900ff9e.

**Pull request merged**
