### PR TITLE
readme: Add new screenshot URLs.

### PR DESCRIPTION
**Pull request by manavmehta**
**What's this PR do?**
Update the screenshots to accomodate new Zulip logo and both the day and night modes

**Screenshots?**

**You have tested this PR on:**
  - [X] macOS

To see what readme will make the page look like, checkout https://github.com/manavmehta/zulip-desktop/tree/ss

### CODE REVIEW

**Comment by akashnimare** [comment]
Remove the chrome org and update the screenshot, will merge :D

**Comment by manavmehta** [comment]
@akashnimare Please review the screenshots :).
Also, do they need to be update in electron/apps too?

**Comment by priyank-p** [comment]
The screenshots includes custom css and the app doesn't look like that out of the box so the screenshots should not include custom css?

**Comment by manavmehta** [comment]
Thanks @priyank-p for pointing out, it totally slipped out of my mind, this being on my app since the stone age 😅

**Pull request merged**
