### PR TITLE
Refinements on multi tab view

### PR DESCRIPTION
**Pull request by zhongyi-tong**
This PR focuses on code quality improvement on the renderer side, along with several features and fixes.
 
screen shot 2017-06-04 at 3 25 36 pm

### Spotlights:
 - **Code refactoring.** Move the logic of WebView and Tab into two separate components. The code is much much more clear to read and maintain. 
 - **Unread messages count.** Each tab now has a badge to show its unread message count. It's tab-level, and app-level badge (macOS dock) will show the sum.
 - **Clearer app title.** The app title now changes according to the active webview, which is consistent with the web app. 
 - **Reload button (for active webview).** The user has the option to reload the active webview, instead of whole app.
 - **DevTools for active webview.** Add a new menu item (with a shortcut) to allow users to debug web contents in the active webview.

### Other changes:
 - Disable text selections in the left sidebar.
 - Disable the outline of WebView when focused.
 - See the commit log.

### CODE REVIEW

**Comment by akashnimare** [comment]
> Clearer app title. The app title now changes according to the active webview, which is consistent with the web app.

Don't change the title of the app, Keep it "Zulip" only (as it gives a feeling of a desktop app, not webapp). 

badge needs more styling - 

image

**Comment by zhongyi-tong** [comment]
Oops, I will fix the style. But would using `Zulip` for all tabs confuses the user? It's not clear which Zulip they are viewing. Or can we use the server's alias instead?

**Comment by zhongyi-tong** [comment]
When number < 1K:
image

When number >= 1K:
image

@akashnimare

**Comment by zhongyi-tong** [comment]
Still working on this issue. There is a bug to fix.

**Comment by zhongyi-tong** [comment]
@akashnimare Should be ready. A large patch. Needs careful review... 🛩

**Comment by akashnimare** [comment]
@geeeeeeeeek this looks good. Can you fix those linting errors so that I can merge it?

**Comment by akashnimare** [comment]
Great work. Thanks @geeeeeeeeek 🚀

**Pull request merged**
