### PR TITLE
Add context menu to right sidebar

### PR DESCRIPTION
**Pull request by kanishk98**
---

**Adds a context menu (displayed on a right click) to the server icons in the right sidebar. Currently includes option to delete the respective organisation.**

**Discussion about this in #599**

**You have tested this PR on:**
  - [ ] Windows
  - [x] Linux/Ubuntu
  - [ ] macOS

### CODE REVIEW

**Comment by akashnimare** [comment]
> I have another question, though. When the organization is removed and a new one is added, the app does not enter the forEach loop referenced in the above comment on first run. I have to restart the app or hit Ctrl + R for the loop to work again.
Is this expected behaviour or should I dig deeper in case this is a bug?

@kanishk98 Okay, there is fix for this. The code for context menu is in the `initActions()` which only gets executed 
when you first load the app. So there are couple of options to make it work 

a) Execute `initActions()` on reloading the view 
```

	reloadView() {
		// Save and remember the index of last active tab so that we can use it later
		const lastActiveTab = this.tabs[this.activeTabIndex].props.index;
		ConfigUtil.setConfigItem('lastActiveTab', lastActiveTab);

		// Destroy the current view and re-initiate it
		this.destroyView();
		this.initTabs();
		this.initActions();
	}
```

b) Extract the following code and make a new function + execute it on first loading the app + on reload -
```js


const $serverImgs = document.querySelectorAll('.server-icons');
		$serverImgs.forEach(($serverImg, index) => {
			$serverImg.addEventListener('contextmenu', e => {
				e.preventDefault();
				const template = [
					{
						label: 'Disconnect organization',
						click: () => {
							dialog.showMessageBox({
								type: 'warning',
								buttons: ['YES', 'NO'],
								defaultId: 0,
								message: 'Are you sure you want to disconnect this organization?'
							}, response => {
								if (response === 0) {
									DomainUtil.removeDomain(index);
									ipcRenderer.send('reload-full-app');
								}
							});
						}
					}
				];
				const contextMenu = Menu.buildFromTemplate(template);
				contextMenu.popup({ window: remote.getCurrentWindow() });
			});
			if ($serverImg.src.includes('img/icon.png')) {
				this.displayInitalCharLogo($serverImg);
			}

			$serverImg.addEventListener('error', () => {
				this.displayInitalCharLogo($serverImg);
			});
		});

```

**Comment by akashnimare** [comment]
Something like this would work -



```js

diff --git a/app/renderer/js/main.js b/app/renderer/js/main.js
index f2cad34..e44e8cc 100644
--- a/app/renderer/js/main.js
+++ b/app/renderer/js/main.js
@@ -198,24 +198,7 @@ class ServerManagerView {
 		}));
 	}
 
-	initActions() {
-		this.initDNDButton();
-		this.$dndButton.addEventListener('click', () => {
-			const dndUtil = DNDUtil.toggle();
-			ipcRenderer.send('forward-message', 'toggle-dnd', dndUtil.dnd, dndUtil.newSettings);
-		});
-		this.$reloadButton.addEventListener('click', () => {
-			this.tabs[this.activeTabIndex].webview.reload();
-		});
-		this.$addServerButton.addEventListener('click', () => {
-			this.openSettings('AddServer');
-		});
-		this.$settingsButton.addEventListener('click', () => {
-			this.openSettings('General');
-		});
-		this.$backButton.addEventListener('click', () => {
-			this.tabs[this.activeTabIndex].webview.back();
-		});
+	initServerActions() {
 		const $serverImgs = document.querySelectorAll('.server-icons');
 		$serverImgs.forEach(($serverImg, index) => {
 			$serverImg.addEventListener('contextmenu', e => {
@@ -250,6 +233,28 @@ class ServerManagerView {
 			});
 		});
 
+	}
+
+	initActions() {
+		this.initDNDButton();
+		this.initServerActions();
+		this.$dndButton.addEventListener('click', () => {
+			const dndUtil = DNDUtil.toggle();
+			ipcRenderer.send('forward-message', 'toggle-dnd', dndUtil.dnd, dndUtil.newSettings);
+		});
+		this.$reloadButton.addEventListener('click', () => {
+			this.tabs[this.activeTabIndex].webview.reload();
+		});
+		this.$addServerButton.addEventListener('click', () => {
+			this.openSettings('AddServer');
+		});
+		this.$settingsButton.addEventListener('click', () => {
+			this.openSettings('General');
+		});
+		this.$backButton.addEventListener('click', () => {
+			this.tabs[this.activeTabIndex].webview.back();
+		});
+
 		this.sidebarHoverEvent(this.$addServerButton, this.$addServerTooltip, true);
 		this.sidebarHoverEvent(this.$settingsButton, this.$settingsTooltip);
 		this.sidebarHoverEvent(this.$reloadButton, this.$reloadTooltip);
@@ -467,6 +472,7 @@ class ServerManagerView {
 		// Destroy the current view and re-initiate it
 		this.destroyView();
 		this.initTabs();
+		this.initServerActions();
 	}
 
 	// This will trigger when pressed CTRL/CMD + R [WIP]


```

**Comment by kanishk98** [comment]
@akashnimare thanks for the suggestions! I'll get to work on this in a day or two - got exams going on, sorry. :(

**Comment by akashnimare** [comment]
Ahh, no issues. I'll go ahead and make those changes from my end. Good luck with the exam :)

**Comment by akashnimare** [comment]
Merged. Thanks, @kanishk98 🚀

**Pull request merged**
