### PR TITLE
settings: Add option to import certificates for linux.

### PR DESCRIPTION
**Pull request by priyank-p**
---

**What's this PR do?**
Add option to import certificate

**Screenshots?**

**You have tested this PR on:**
  - [ ] Windows
  - [ ] Linux/Ubuntu
  - [X] macOS

### CODE REVIEW

**Comment by akashnimare** [comment]
@lonerz, @synicalsyntax what does the `size:XL` labels represent here 😕

**Comment by synicalsyntax** [comment]
It's a new feature per @rishig's request: see https://github.com/zulip/zulipbot/issues/135

I can disable the feature for this repository if you want, but it'd also eliminate activity checks from claimed issues.

**Comment by akashnimare** [comment]
@synicalsyntax no, it's great. I thought it's the t-shirt size or what 😆

**Comment by priyank-p** [comment]
Argh, i will close this up as well! This has two diffrent PR in one and one part does not work. I will clean it up and we need check it so closing this for now.

**Pull request closed without merging**
