### PR TITLE
Update changelog.md

### PR DESCRIPTION
**Pull request by SankalpSh**
---

**What's this PR do?**
+Removed spelling mistakes.

**Any background context you want to provide?**
+No.

**Screenshots?**

**You have tested this PR on:**
  - [ yes] Windows
  - [ yes] Linux/Ubuntu
  - [ ] macOS

### CODE REVIEW

**Comment by SankalpSh** [comment]
Please let me know of any changes to make to add the pull request to be merged properly.

**Review by kanishk98 — COMMENTED** [review]
Thanks for working on this. I noticed a couple of things you missed:
1. Line 422: `Now we only depends on menu accelerators for keyboard shortcuts` (change to depend)
2. Line 637: Enhancement spelling error

**Comment by kanishk98** [comment]
Looks good to me. 
Having made a couple of mistakes with git myself, I'd suggest you squash the commits and then force push your local branch (`git push -f`) so that the upstream repo's master can maintain a clean git history. 
If you're not too comfortable with the command line, you can always use a graphical git client. [Here]'s how to squash commits in GitKraken, for example.

**Comment by SankalpSh** [comment]
@kanishk98 I have edited and committed all the changes on github web.
Do not know how to proceed now? Help.

**Comment by akashnimare** [comment]
Merged. Thanks, @SankalpSh, @kanishk98.

**Pull request merged**
