### PR TITLE
[WIP] Fix online check if using proxy

### PR DESCRIPTION
**Pull request by superbiche**
**What's this PR do?**
This PR tries to mitigate (re)connection issues experienced by users behind a proxy as raised in #591 and discussed [here](https://chat.zulip.org/#narrow/stream/16-desktop/topic/no.20internet).  

If `is-online` returns `true`, we're online
If `is-online` returns `false`, no proxy enabled, we're offline
If `is-online` returns `false` **and we use a proxy**, we:
- get the list of domains  
- prepare a properly setup `request` with `ca` and `proxy` options for each domain to fetch the `favicon.ico`
- run a `Promise.race()` against all the requests, ending whenever one domain's favicon has been reached (**means we're kinda online regarding our Zulip instances**)

**Any background context you want to provide?**
The package used to check every 1.5s if we're online/offline, `is-online`, relies on the `got` package which is not compatible with proxies. 
Given that `got` is not compatible with proxy connections, and that there's so many ways a test could work in a given setup and not on another, the best way seems to test for Zulip instances as this is the most relevant.

**Screenshots?**

* Behavior with online/offline/online : https://d.pr/i/6I7nCb  
* Behavior with offline/online : https://d.pr/i/NVWVSG

**You have tested this PR on:**
macOS Mojave 10.14.1

**Important notes:**

I've deliberately commented some code to help test this implementation without a proxy and reach the favicon test code. Would be really amazing if someone could try it with a proxy!

**This is very far from being either a perfect solution but, for me, it's much more valuable being able to reach a Zulip domain than Google or OpenDNS, as what we want to give the user is an insight about whether he can use a Zulip domain and nothing else.**  
Maybe cleaner solutions exist that would work in proxy setups, but when even reaching Google or OpenDNS fails in some very specific setups, and if you can't reach anything else than your Zulip domains, you should still be able to use Zulip.

Feel free to share your thoughts :)

### CODE REVIEW

**Comment by abhigyank** [comment]
I feel the addition of `requestOptions` in `request-util.js` would make our code very clean and easier to write. I think it deserves a separate PR with all places of `request` changed to `requestOptions`. @superbiche Would you interested in doing that? Then you can this rebase this PR above that commit (once merged).

**Comment by superbiche** [comment]
Yes I’ll start with doing that.

[image: Logo]

Michel Tomas / Freelance Web Developer
michel@superbiche.co <michel@wisenwild.com> / +33 6 08 05 94 27
[image: Skype] <skype:webiche?add> [image: Twitter]
<https://twitter.com/superbiche> [image: LinkedIn]
<https://www.linkedin.com/in/micheltomas> [image: Github]
<https://github.com/superbiche>

On 1 December 2018 at 14:13:53, Abhigyan Khaund (notifications@github.com)
wrote:

I feel the addition of requestOptions in request-util.js would make our
code very clean and easier to write. I think it deserves a separate PR with
all places of request changed to requestOptions. @superbiche
<https://github.com/superbiche> Would you interested in doing that? Then
you can this rebase this PR above that commit (once merged).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/zulip/zulip-electron/pull/598#issuecomment-443425383>,
or mute the thread

**Comment by akashnimare** [comment]
@superbiche let me know if you need any help in this.

**Comment by akashnimare** [comment]
Some part of this PR has been merged in #643.

**Pull request closed without merging**
