### PR TITLE
Improve the French translation

### PR DESCRIPTION
**Pull request by moeenio**
**What's this PR do?** Improves the French translation.

**You have tested this PR on:**
  - [ ] Windows
  - [ ] Linux/Ubuntu
  - [x] macOS

### CODE REVIEW

**Comment by moeenio** [comment]
Look like I can't translate the strings in the sidebar (tried with Enable Do Not Disturb)

**Comment by akashnimare** [comment]
@locness3 hey, thanks for the contribution. Please check -
https://github.com/zulip/zulip-desktop/blob/master/app/translations/README.md
https://zulip.readthedocs.io/en/latest/translating/internationalization.html

**Comment by moeenio** [comment]
Yes, what should I do with what's on this page ? Use transifex ? Run some build command ? @akashnimare

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by akashnimare** [comment]
@locness3 yeah, please use Transifex and update the French translation there :)
After making an account there you should update [this](https://www.transifex.com/zulip/zulip/translate/#fr/desktopjson/184140586?q=reviewed%3Ano) file.

**Comment by moeenio** [comment]
Uh yes but how do i access the project

**Comment by akashnimare** [comment]
@timabbott do we need to send an invite here?

**Comment by moeenio** [comment]
I believe that yes. My transifex username is locness3.

**Comment by moeenio** [comment]
Hello, could you send me a transifex invite? My username is locness3 @akashnimare

**Comment by akashnimare** [comment]
@manavmehta did we pick this changes on Transifex?

**Comment by manavmehta** [comment]
@akashnimare  Sorry, missed it somehow. I'll incorporate these changes while fixing the transifex.

**Pull request closed without merging**
