### PR TITLE
macOS: Update dock icon.

### LINKED ISSUE #787: macOS dock icon is too large
The icon used on the macOS dock is too large and looks out of place compared to other round icons in the dock.
image

---
- **Operating System**:
  - [ ] Windows
  - [ ] Linux/Ubuntu
  - [x] macOS

### PR DESCRIPTION
**Pull request by adityamudgil2505**
Added inner padding (transparent) of 30px to the icon having size 512x512.

We are getting too large size because other application logos are giving inner padding of 30px whereas Zulip application icon is giving 0px inner padding.
Detailed explanation in term of image

After giving inner padding of 30px, now our application logo is looking perfect.

Working image

**Note:** The actual size of the icon after giving padding will remain the same that is 512x512.
Solve Issue #787 

**You have tested this PR on:**
  - [ ] Windows
  - [ ] Linux/Ubuntu
  - [x] macOS

### CODE REVIEW

**Comment by akashnimare** [comment]
This is great. Will check locally and see if it fixes our problem.

**Comment by akashnimare** [comment]
This is how it looks on my system (looks a bit smaller I think) -
image

**Comment by adityamudgil2505** [comment]
I think we can give padding of 25px rather than 30px which will look appropriate.

**Comment by adityamudgil2505** [comment]
@akashnimare When the change to give padding of 25 px doesn't have much impact on size. Therefore 20px padding looks perfect.
Image 1
Image 2

**Comment by akashnimare** [comment]
Looks better now. Merging. Thanks, @adityamudgil2505.

**Comment by akashnimare** [comment]
The padding is visible in the colourless icon -

image

@abhigyank @manavmehta gotta update the icons.

**Pull request merged**
