### PR TITLE
Remove third party certificate modal popups

### PR DESCRIPTION
**Pull request by jbarna-panjiva**
---

**What's this PR do?**
This fixes the issue #1119 

**Any background context you want to provide?**
This popup occurs constantly throughout the day while using Zulip for myself and all of my coworkers. The popup modal overlays all other system windows and usually pops up multiple times in a row, sometimes jumping between screens (just for added terror 🙃 )

As discussed in the issue, the popup should occur if there is a certificate issue with the server domain of the organization. However for any other third party URL, such as thumbnails, the popups are not necessary.

**Screenshots?**
Please see the screenshots shared in the linked issue

**You have tested this PR on:**

- [ ] Windows
- [ ] Linux/Ubuntu
- [x] macOS

### CODE REVIEW

**Comment by jbarna-panjiva** [comment]
@timabbott Is there anything I can do to help the organization include this change? Everyone at my organization does not use zulip-desktop because of this issue.

**Comment by alice-kaanta** [comment]
Could we get this change in? I'm the last Zulip Desktop user standing, and I've calculated that I spend up to 5 minutes a day batting down this modal just so I can find out what engineering said about that bug I filed.  This modal has a particular jack-in-the-box quality, such that I end up having to hit it up to 9 times in a row. Generally I view this sort of thing as part of my daily sacrifice to the IT gods, but honestly I'd rather not.  

Thank you!

**Comment by nooblag** [comment]
Yes, please! I'd also love to see this merged. Thanks!

**Comment by VincePhoenixDev** [comment]
Came here to add that it would be nice to see this merged. Seems there are conflict though @jbarna-panjiva

**Pull request closed without merging**
