### PR TITLE
Add support for system-wide certificates.

### PR DESCRIPTION
**Pull request by kanishk98**
---

**What's this PR do?**

If there are no pre-existing certs associated with a certain domain, Zulip will now load certs from the system store for Windows and macOS. This allows admins in the enterprise to deploy Zulip across computers by using the system-wide cert store.

**You have tested this PR on:**
  - [x] Windows
  - [ ] Linux/Ubuntu
  - [x] macOS

### CODE REVIEW

**Comment by kanishk98** [comment]
Alright, added support for Linux, but I was only able to run some basic checks using a VM. @muskankhedia would you mind checking out this PR and letting us know if it works as expected?

**Comment by kanishk98** [comment]
Something I forgot to mention when submitting this PR: it's best to delete the `win-ca/pem` folder from `node_modules` when publishing the app. @akashnimare if you'd like to have a look at this, [here's](https://github.com/ukoloff/win-ca#clear-pem-folder-on-publish) the link to the author's comments.

**Comment by akashnimare** [comment]
@kanishk98 I completely forgot about this PR. Is it good to merge?

**Comment by kanishk98** [comment]
I’m pretty sure it was good to merge, but I’ll have a look at it once again later tonight and rebase it against master. 
I’d also worked on publishing an npm module [linux-ca](https://www.npmjs.com/package/linux-ca) based on the work in this PR. @akashnimare if it’s fine with you, maybe we could refactor this PR to include the Linux cert check as a method from said package?

**Comment by manavmehta** [comment]
@kanishk98 Since it looks like [linux-ca](https://www.npmjs.com/package/linux-ca) is now available via npm, is there some more work left on the PR or should we make the necessary changes corresponding to the module and go ahead?

**Comment by kanishk98** [comment]
@manavmehta things should be good to go. I can help with the PR if you run into any issues, of course.

**Comment by andersk** [comment]
If I understand correctly, switching from `request` to `electron.net` (#886) will make this unnecessary. I’d prefer to resolve this that way.

**Comment by manavmehta** [comment]
@andersk Sorry I couldn't follow that. Does `electron.net` support enterprise-certs out of the box?

**Comment by akashnimare** [comment]
@manavmehta yup, if we use `electron.net`, we don't need to handle the CA thing.

**Comment by andersk** [comment]
Closing in favor of the `electron.net` migration (#993), which was merged in version 5.4.0.

**Pull request closed without merging**
