### PR TITLE
shortcuts-menu: Add a tip-section to link to webapp's built-in hotkeys.

### PR DESCRIPTION
**Pull request by abhigyank**
Fixes: #459
**Screenshot**
screenshot from 2018-03-30 00-22-38

### CODE REVIEW

**Comment by timabbott** [comment]
Visually, looks great to me (though maybe we should try putting it at the top and see how it goes).  I would call them "Keyboard shortcuts", not "hotkeys", for consistency.

Tagging @rishig for an opinion on the label text; I'm not sure it's quite right.

**Comment by rishig** [comment]
Yeah, I think putting on top makes sense. Though would it possibly make sense just to duplicate the web shortcuts information here?

**Comment by rishig** [comment]
Or maybe we can frame it as: "Zulip's shortcuts are primarily documented [here]. In addition, .."

**Comment by akashnimare** [comment]
@rishig would it make sense to append app's shortcut into the web app keyboard shortcut's popup (and remove the shortcut page from app's setting page). We could introduce a tab like **Desktop shortcut** or something. This is because we have two shortcuts within the app one is in the Menu item which opens the webapp shortcut popup and the other one is in the desktop app shortcut's page which only shows the app shortcuts. We just don't want user to get confused between both the shortcuts. We could also add all the webapp shortcuts (that popup) into the app's shortcut page.

**Comment by timabbott** [comment]
We can't duplicate the webapp shortcuts here, because the user may be connected to multiple organizations which might have different Zulip versions with different sets of hotkeys.  So I think it's better to not try to inline that data into the desktop app.

**Comment by rishig** [comment]
I see. Would it be possible to go in the other direction, as Akash suggested? E.g. dynamically embed the desktop shortcuts into the webapp keyboard shortcuts help? 

As a quick solution though, we can put this at the top:
 "Zulip's shortcuts are primarily documented [here]. A few additional shortcuts are documented below."

Also, most of the current shortcuts (cut/copy/paste, zoom, etc) probably work in the webapp too, for all common browsers? So arguably we could add them to the webapp shortcut list, though I think we'd need a better UI for displaying them.

**Comment by timabbott** [comment]
I think we should not block integrating the link here on doing some more complicated with trying to duplicate shortcuts.  I think it's actually kinda a pain to do something nice with that, and I think 90% of the value is just having it be clear that there's two sets (especially since they basically are for different things -- e.g. one is for controlling the app in terms of things like what org you're in).

For the text, I think this is fine:

"These desktop app shortcuts extend the <a>Zulip webapp's keyboard shortcuts</a>"

**Comment by akashnimare** [comment]
@timabbott make sense. @abhigyank can you update the text so that we can merge this.

**Comment by akashnimare** [comment]
Merged in https://github.com/zulip/zulip-electron/commit/ceaf13dee2fbae479b51f528359f6d58bc39ba1c.

**Pull request closed without merging**
