### PR TITLE
Exposing Whitelisted Protocols to User Settings

### PR DESCRIPTION
**Pull request by jonassorgenfrei**
**What's this PR do?**

It exposes the whitelisted protocols list so users can add additional protocols that should not use the link wrapper. 

**You have tested this PR on:**

- [x] Windows
- [x] Linux/Ubuntu

### CODE REVIEW

**Comment by jonassorgenfrei** [comment]
Addressed this issue: 
https://github.com/zulip/zulip-desktop/issues/1284

**Comment by jonassorgenfrei** [comment]
Tested for Linux (Ubuntu) today too!

**Comment by jonassorgenfrei** [comment]
@andersk @timabbott could you take a look on this PR?

**Comment by jonassorgenfrei** [comment]
Heyhye, can someone take a look into this PR so it can be merged. This will allow linkifiers to work based on settings whitlisting :)

**Comment by timabbott** [comment]
Can you clean up the PR to follow our contributing guidelines? Among other things, check out our [GitHub guide](https://zulip.readthedocs.io/en/latest/git-guide.html) and [commit guidelines](https://zulip.readthedocs.io/en/latest/contributing/commit-discipline.html) for more details.

**Comment by Carnage78** [comment]
it makes sense to immediately add tel: and sip: protocols to the white list

**Comment by jonassorgenfrei** [comment]
I messed up this branch, will fix and reopen

**Comment by jonassorgenfrei** [comment]
MOVED TO: https://github.com/zulip/zulip-desktop/pull/1401

**Pull request closed without merging**
