### PR TITLE
Provide silent & seamless reload for the app

### LINKED ISSUE #212: Forced focus regain on reconnecting to the server
When the user disconnects from the internet and reconnects, the app regains focus, even causing a workspace switch. I believe the reconnection to the server triggers this.

OS: Elementary OS 0.4 (Ubuntu 16.04)
Steps to reproduce: Focus another window. Disable networking. Enable networking. Wait.
Expected incorrect behavior: Zulip Desktop app automatically regains focus.
Expected behavior: Nothing/desktop notification saying "Reconnected to server".

### PR DESCRIPTION
**Pull request by zhongyi-tong**
- Replace `reload-main` with **seamless** `reload-viewer`.
 - Fix #212. No longer regains focus after reconnection.

### CODE REVIEW

**Comment by akashnimare** [comment]
LGTM 👍 .  Thanks, @geeeeeeeeek.

**Comment by akashnimare** [comment]
@geeeeeeeeek Should we also add a shortcut to reload the browser window? Something like `CMD+SHIFT+R` that would be useful in some cases. Thoughts?

**Comment by zhongyi-tong** [comment]
cmd R will reload the app now.
Akash Nimare <notifications@github.com>于2017年7月18日 周二下午6:17写道：

**Comment by akashnimare** [comment]
CMD+R only reloads the webview, right? I'm talking about `mainWindow.reload()` event which reloads the app.

**Comment by zhongyi-tong** [comment]
Oh. I see. But is it really necessary? If it's for debugging purpose, we
can reload the app in the webview.
Akash Nimare <notifications@github.com>于2017年7月19日 周三上午4:48写道：

**Comment by akashnimare** [comment]
Yeah, mostly for debugging purpose :D

**Comment by zhongyi-tong** [comment]
Ok, I will add another shortcut. 😀
Akash Nimare <notifications@github.com>于2017年7月19日 周三上午4:53写道：

**Comment by akashnimare** [comment]
Added in https://github.com/zulip/zulip-electron/commit/505fea0e91c9e69228a469057d8d21ddbde5837b.

**Pull request merged**
