### PR TITLE
Check for zulip.ogg only if server error is 404, for old Zulip servers.

### PR DESCRIPTION
**Pull request by Swapnilr1**
---

**What's this PR do?**
Fixes issue #573 

**Any background context you want to provide?**

**Screenshots?**

**You have tested this PR on:**
  - [ ] Windows
  - [x] Linux/Ubuntu
  - [ ] macOS

@akashnimare @abhigyank Please review this (corrected version of https://github.com/zulip/zulip-electron/pull/631 ).

### CODE REVIEW

**Comment by timabbott** [comment]
Can we include unit tests for this logic?  It's getting complicated.

**Comment by Swapnilr1** [comment]
@timabbott Sure, I will add a unit test for this after I read some documentation regarding tests. Regarding the logic, I am not sure how to simplify it, so I would really appreciate some help if you think I have done it in a more complicated manner than is possible.

**Comment by timabbott** [comment]
That wasn't a comment on the logic changes here -- it's just that this part of the codebase is the sort of thing with several conditionals that should really have unit tests.  And that changing it is a good opportunity to write that test suite (saves a lot of manual testing to understand what happens in each case).

**Comment by Swapnilr1** [comment]
@timabbott As per https://chat.zulip.org/#narrow/stream/16-desktop/topic/Unit.20Tests/near/705350 I think I need to wait for #526 to get merged first, and then I can write a unit test.

**Comment by akashnimare** [comment]
@kanishk98 we can close this, right?

**Comment by kanishk98** [comment]
Yeah, the new validation logic should take care of this instead.

**Pull request closed without merging**
