### PR TITLE
Feature/settings page

### PR DESCRIPTION
**Pull request by zhongyi-tong**
c

Setting items we discussed before:
 - Show tray icon
 - Show/hide desktop notifications
 - Mute desktop notifications
 - Disable/enable spellchecker
 - Auto login

The framework of settings page is done. But not sure we can finish them all in 1.0.0.

### CODE REVIEW

**Comment by timabbott** [comment]
Nice!  I think it's totally reasonable to merge an initial settings page with like 1 setting on the "General" screen and then plan to add the rest as their own issues, to avoid the framework getting blocked on figuring out all the settings we want.

For things like "show desktop notifications", do you think we want those to sync with the similar webapp/server setting, or not?  I think that's the main interesting question here :)

**Comment by zhongyi-tong** [comment]
screen shot 2017-07-03 at 2 09 46 am
screen shot 2017-07-03 at 2 09 53 am
screen shot 2017-07-03 at 2 10 46 am

**Comment by zhongyi-tong** [comment]
@timabbott For things like "show desktop notifications", I think it's different per server. We could have a overall toggle that turns on/off all notifications. If turned on, use server-specific preference. Otherwise, no notifications at all. 😀

**Comment by akashnimare** [comment]
This looks great for now. Merging. Thanks, @geeeeeeeeek 🚀

**Pull request merged**
