### PR TITLE
mac: Support pkg installer on macOS.

### PR DESCRIPTION
**Pull request by akashnimare**
Add support for pkg on macOS.

To-dos -
- [x] Check installer
- [x] Test auto-updates

### CODE REVIEW

**Comment by andersk** [comment]
What happened to `package-lock.json`?

**Comment by akashnimare** [comment]
Yeah, was wondering the same. Maybe I was on the other PR where I did an npm install and then switched to master and checked out to a new branch and did npm install again.

**Comment by andersk** [comment]
Hmm, my `npm` does that too now. I guess we should commit the `package-lock.json` change—but separately, so it doesn’t get mixed in with other changes.

**Comment by akashnimare** [comment]
Installer works fine. Just need to test auto-updates.

**Pull request merged**
