### PR TITLE
sidebar and menu: add option to copy zulip url

### LINKED ISSUE #649: Add "Copy Zulip URL" to a few places.
For the right click menu on the organization logo, we should add "Copy Zulip URL". We should also add "Copy Zulip URL" to one of the menus at the top (maybe Window?)

For context, one of the goals with this is to teach users what the Zulip URL is. 

Some discussion: https://chat.zulip.org/#narrow/stream/16-desktop/topic/Zulip.20URL

### PR DESCRIPTION
**Pull request by vsvipul**
**What's this PR do?**
For the right click menu on the organization logo, adds "Copy Zulip URL" option.
closes #649 

**Screenshots?**
screenshot from 2019-02-14 19-18-45

**You have tested this PR on:**
  - [ ] Windows
  - [x] Linux/Ubuntu
  - [ ] macOS

### CODE REVIEW

**Comment by vsvipul** [comment]
@rishig how should i go on to add the option to window menu ?

**Review by abhigyank — APPROVED** [review]
Works fine.

**Comment by vsvipul** [comment]
i have also added the option to file menu for now as discussed @rishig @abhigyank ..

**Review by abhigyank — COMMENTED** [review]
@vsvipul  You need to add it for the MacOS separately under `getDarwinTpl` function as well.

**Comment by vsvipul** [comment]
> @vsvipul You need to add it for the MacOS separately under `getDarwinTpl` function as well.

added it :) Thanks

**Comment by vsvipul** [comment]
@akashnimare @abhigyank a reminder on this.

**Comment by akashnimare** [comment]
Thanks, @vsvipul.

**Pull request merged**
