### PR TITLE
Fix issue #565

### PR DESCRIPTION
**Pull request by ThePiyushGupta**
---

**What's this PR do?**
This PR fixes issue #565 
**Any background context you want to provide?**

**Screenshots?**

**You have tested this PR on:**
  - [x] Linux/Ubuntu
  - [ ] Mac/Os
  - [ ] Windows

### CODE REVIEW

**Comment by akashnimare** [comment]
@ThePiyushGupta thanks for working on this. Few changes -
* Can you remove the changes related to the network setting? 
* We just need to hide the window when the start to minimized is on so you don't need to introduce that tray setting option.

**Comment by ThePiyushGupta** [comment]
@akashnimare So what you mean is that alwaysstartminimised =alwaysstartintray and i don't need to create another option in settings.
Secondly all the changes related to issue #540 should be undone

**Comment by akashnimare** [comment]
> So what you mean is that alwaysstartminimised =alwaysstartintray and i don't need to create another option in settings.

Correct. Also, checkout - https://zulip.readthedocs.io/en/latest/contributing/index.html for better commit guidelines.

**Comment by ThePiyushGupta** [comment]
It's better i create a new pull request

**Pull request closed without merging**
