### PR TITLE
debian-installer: add apt repo for debian

### PR DESCRIPTION
**Pull request by priyank-p**
This will register apt repo after installation for debian
Fixes: https://github.com/zulip/zulip-electron/issues/283

### CODE REVIEW

**Comment by akashnimare** [comment]
@cPhost have you tested this?

**Comment by priyank-p** [comment]
~~TBH, i have no idea how to i am pretty sure we need someone that has debian OS~~

**Comment by priyank-p** [comment]
~~@akashnimare The best way to test is it `pre-release` or `beta` release this and pretty sure as long as the bash file is correct it should work and for now at least it would log out everything we can later disable logging by pointing the output to `>dev>null`.~~
EDIT: testing using c9 ide.

**Comment by akashnimare** [comment]
@cPhost this is how you can test it -
* Downgrade the app version in both package.json 
* Build the installer using `npm run dist`
* Install the deb file
* Check if the repo is successfully added in `/etc/apt/sources.list.d/zulip.list`
* Run `sudo apt-get update` and `sudo apt-get upgrade`

You need to add the check if the apt repo is already there using something like [this](https://askubuntu.com/questions/381152/how-to-check-if-ppa-is-already-added-to-apt-sources-list-in-a-bash-script) or [this](https://github.com/Microsoft/vscode/blob/bfc4e3d780ddbcf8802d9ddc61e3b440af3cae5b/resources/linux/debian/postinst.template#L67) otherwise it will throw error -

```shell
➜  zulip-electron git:(347) ✗ sudo apt-get update                        
Hit:1 http://ppa.launchpad.net/noobslab/apps/ubuntu xenial InRelease
Hit:2 http://security.ubuntu.com/ubuntu xenial-security InRelease                                                             
Hit:3 http://us.archive.ubuntu.com/ubuntu xenial InRelease                                                                         
Hit:4 http://ppa.launchpad.net/otto-kesselgulasch/gimp/ubuntu xenial InRelease
Hit:5 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease                                  
Hit:6 http://ppa.launchpad.net/videolan/stable-daily/ubuntu xenial InRelease
Hit:7 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease                                
Hit:8 http://ppa.launchpad.net/groonga/ppa/ubuntu xenial InRelease       
Ign:9 https://dl.bintray.com/zulip/debian stable InRelease                    
Hit:10 http://ppa.launchpad.net/tabbott/zulip/ubuntu xenial InRelease
Get:11 https://dl.bintray.com/zulip/debian stable Release [1,840 B]
Hit:11 https://dl.bintray.com/zulip/debian stable Release 
Reading package lists... Done                             
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/zuliptest.list:1 and /etc/apt/sources.list.d/zuliptest.list:2
W: Target Packages (main/binary-i386/Packages) is configured multiple times in /etc/apt/sources.list.d/zuliptest.list:1 and /etc/apt/sources.list.d/zuliptest.list:2
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/zuliptest.list:1 and /etc/apt/sources.list.d/zuliptest.list:2
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/zuliptest.list:1 and /etc/apt/sources.list.d/zuliptest.list:2
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/zuliptest.list:1 and /etc/apt/sources.list.d/zuliptest.list:2
W: Target DEP-11 (main/dep11/Components-amd64.yml) is configured multiple times in /etc/apt/sources.list.d/zuliptest.list:1 and /etc/apt/sources.list.d/zuliptest.list:2
W: Target DEP-11-icons (main/dep11/icons-64x64.tar) is configured multiple times in /etc/apt/sources.list.d/zuliptest.list:1 and /etc/apt/sources.list.d/zuliptest.list:2
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/zuliptest.list:1 and /etc/apt/sources.list.d/zuliptest.list:2
W: Target Packages (main/binary-i386/Packages) is configured multiple times in /etc/apt/sources.list.d/zuliptest.list:1 and /etc/apt/sources.list.d/zuliptest.list:2
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/zuliptest.list:1 and /etc/apt/sources.list.d/zuliptest.list:2
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/zuliptest.list:1 and /etc/apt/sources.list.d/zuliptest.list:2
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/zuliptest.list:1 and /etc/apt/sources.list.d/zuliptest.list:2
W: Target DEP-11 (main/dep11/Components-amd64.yml) is configured multiple times in /etc/apt/sources.list.d/zuliptest.list:1 and /etc/apt/sources.list.d/zuliptest.list:2
W: Target DEP-11-icons (main/dep11/icons-64x64.tar) is configured multiple times in /etc/apt/sources.list.d/zuliptest.list:1 and /etc/apt/sources.list.d/zuliptest.list:2

```

**Comment by akashnimare** [comment]
Also, we need to add a post-uninstall script which will remove all these things which are added through post-install script.

**Comment by priyank-p** [comment]
@akashnimare can you give me the script for that so i can put it in there.

**Comment by akashnimare** [comment]
This is what you have to figure out :)

**Comment by priyank-p** [comment]
@akashnimare Works!
screen shot 2017-12-04 at 7 53 56 pm
screen shot 2017-12-04 at 8 00 47 pm

**Comment by akashnimare** [comment]
> You need to add the check if the apt repo is already there using

^^ it's remaining here.

**Comment by priyank-p** [comment]
@akashnimare done

**Comment by akashnimare** [comment]
Tested, works as expected. Merged, thanks @cPhost 🚀

**Pull request merged**
