### PR TITLE
Provide keyboard shortcut to switch between servers.

### PR DESCRIPTION
**Pull request by zhongyi-tong**
screen shot 2017-07-10 at 2 40 25 pm

### CODE REVIEW

**Comment by timabbott** [comment]
@geeeeeeeeek what keys are you using?  

CC @synicalsyntax @lonerz, we will probably want to figure out a way to document the hotkey(s) only available in the desktop app (like switching organization).

**Comment by zhongyi-tong** [comment]
@timabbott It's displayed in the sidebar. `CmdOrCtrl+${tabIndex}` are used.

**Comment by zhongyi-tong** [comment]
@akashnimare @timabbott Closed since changes in this PR is part of #202.

**Comment by timabbott** [comment]
I feel like those keyboard shortcuts have maybe too must visual weight in the sidebar; maybe we should use a lighter color or make them only visible on hover, or something?

**Comment by zhongyi-tong** [comment]
@timabbott This is how Slack looks like.. Maybe I can try a lighter color.

**Pull request closed without merging**
