### PR TITLE
improved reconnect error page

### LINKED ISSUE #862: Improve reconnect error page.
The visual appearance of the reconnect error page we see when there are problems with the internet connection can be significantly improved.

Screenshot from 2020-01-14 18-48-18

- **Clear steps to reproduce the issue**:
Start the app without an internet connection

### PR DESCRIPTION
**Pull request by iyashwantsaini**
---

**What's this PR do?**
Improved reconnect error page fixes #862

**Any background context you want to provide?**
Improved network.html and network.css 

**Screenshots?**
**You have tested this PR on:**
  - [x] Windows
  - [x] Linux/Ubuntu
  - [ ] macOS

### CODE REVIEW

**Comment by akashnimare** [comment]
@meyash hey, thanks for the contributing to the project. This looks nice. I think there is still a room for improvements for the content (list items, button alignment). Also, I would suggest please discuss the changes, ask for feedback etc in #desktop stream on https://chat.zulip.org/ and then open a PR. This will save a lot of your time :)

**Comment by iyashwantsaini** [comment]
@timabbott @vsvipul 
request for a review

**Comment by akashnimare** [comment]
>  I think there is still a room for improvements for the content (list items, button alignment)

@meyash can you try out some UI for this? Once done, we can merge this.

**Comment by iyashwantsaini** [comment]
@akashnimare 
I have improved the list and buttons
net

**Comment by vsvipul** [comment]
@meyash  Doesn't look good enough. We need to keep it clean and make it look good simultaneously.

**Comment by iyashwantsaini** [comment]
> @meyash Doesn't look good enough. We need to keep it clean and make it look good simultaneously.

Can you suggest some changes i can  make?

**Comment by iyashwantsaini** [comment]
How can i fix the conflicts?

**Comment by vsvipul** [comment]
@meyash  Read a tutorial online on how to do so. Just google the words on how to do so.

**Pull request closed without merging**
