### PR TITLE
Urgent electron upgrade

### PR DESCRIPTION
**Pull request by kanishk98**
---

**What's this PR do?**

Upgrades the Electron version to 5.0.6 to deal with Google login issues some users have been facing. 

**Any background context you want to provide?**

I chose this version because this had been well-tested in an earlier PR (#781). 
@akashnimare I tried testing the auto-update, but ran into the same issue where Windows was unable to locate `Zulip.exe`. Please let me know if there's an alternative solution. 

**You have tested this PR on:**
  - [x] Windows
  - [ ] Linux/Ubuntu
  - [ ] macOS

### CODE REVIEW

**Comment by akashnimare** [comment]
@kanishk98  Great, let me check. How's the builder + updater behaving on this version?

**Comment by kanishk98** [comment]
It's throwing errors when I run `npm run dist`. I'm still looking into whether this is because of my Windows `npm` setup or something else. 

Please note, though - this still is just an update. I think we'll need to rebase and merge #D831 to fully fix the GitHub and Google login issues. Working on that right now.

**Comment by akashnimare** [comment]
Can't update the error is still there -

image

**Comment by kanishk98** [comment]
Updated to 6.1.4, but looks like the error still persists. Working on 7.1.2 right now.

**Comment by timabbott** [comment]
We should also be testing with the Google issue; that GitHub warning at least looks like one could ignore it if one wanted to.  It's possible that an Electron upgraded is needed for Google but something else or in addition for GitHub.

**Comment by andersk** [comment]
Similar to the Google issue, we should delegate to the real system browser for the GitHub OAuth flow.

**Comment by akashnimare** [comment]
> Similar to the Google issue, we should delegate to the real system browser for the GitHub OAuth flow.

Yeah, that is the plan.

**Comment by timabbott** [comment]
We merged the upgrade to Electron v6 today, which incorporated almost all of these changes.  Thanks for your work on this @kanishk98!

**Pull request closed without merging**
