### PR TITLE
Create zh-CN.json

### PR DESCRIPTION
**Pull request by cqlilon**
Add simplified Chinese translation

---

**What's this PR do?**

**Any background context you want to provide?**

**Screenshots?**

**You have tested this PR on:**
  - [ ] Windows
  - [ ] Linux/Ubuntu
  - [ ] macOS

### CODE REVIEW

**Comment by priyank-p** [comment]
@cqlilon Thanks for translation!

@kanishk98 can we use this translation in the PR to show it in the app?

**Comment by kanishk98** [comment]
> @kanishk98 can we use this translation in the PR to show it in the app?

Sure, I'll add this. Since we're working with more menu items in #730, though, I need one clarification. @cqlilon can you tell me what I should put in the `zh` field in [here](https://github.com/zulip/zulip-desktop/blob/427c86afafaa048e189c3593afeb962c021e79a0/tools/locale-helper/supported-locales.js#L20)? I found 2-3 options after a web search and wasn't sure which to include. 

(We'll use the translation provided by you, but in case we have more menu items in the future, we'll need to rely on this to show Google-provided translations).

**Comment by cqlilon** [comment]
@kanishk98 you should pull in the `zh-hans` field in file tools/locale-helper/supported-locales.js .
"zh-hans": "中文简体"

**Comment by cqlilon** [comment]
@kanishk98 Don't worry,  I will continue to follow up the project and do a good job in Chinese translation.

**Comment by akashnimare** [comment]
@kanishk98 you have pulled this in the menu translation PR, right? If yes, we can close this.

**Comment by kanishk98** [comment]
@akashnimare yeah, I have. We can close this.

**Comment by akashnimare** [comment]
@cqlilon thanks for working on this.

**Pull request closed without merging**
