### PR TITLE
index.html: fix div indentation

### PR DESCRIPTION
**Pull request by vsvipul**
Fix a div indentation in index.html file

**You have tested this PR on:**
  - [ ] Windows
  - [x] Linux/Ubuntu
  - [ ] macOS

### CODE REVIEW

**Comment by abhigyank** [comment]
Surprised this existed! @akashnimare  shouldn't `xo` be taking care of such things?

**Comment by akashnimare** [comment]
> Surprised this existed! @akashnimare shouldn't xo be taking care of such things?

I don't think that xo covers that file 🤔

**Comment by abhigyank** [comment]
Ideally it should, shouldn't it?
I think we can merge this PR but have a look at the `xo` config for not covering this @akashnimare.
@vsvipul Can you look v into that, and create a PR of you find a fix?

**Comment by vsvipul** [comment]
Sure, I'll look into it

**Comment by priyank-p** [comment]
xo is basically provides rules pre-configured on top of eslint and is a JavaScript linter so that's why it can't lint html files. Though there might be eslint plugin you can add in xo config that provides html linting but that very unlikely. The correct way to lint html files would be using a separate html linter here.

**Comment by akashnimare** [comment]
@vsvipul can you look into this, I think we could use `eslint-html-plugin` with `xo`.

**Comment by vsvipul** [comment]
@akashnimare i looked into and found that `eslint-html-plugin` is used to lint JS contained in `<script>` tags in html files. It is not for linting HTML files. The appropriate approach here would be use a linter that can lint all html, css and js files , and not only JS. We need to find something like git-lint (pip) for npm and replace it with xo.

**Comment by vsvipul** [comment]
Fixed in #726 . So, closing this.

**Pull request closed without merging**
